# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-19 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='extra link')),
                ('date_release', models.DateTimeField(blank=True, null=True, verbose_name='date released ')),
                ('date_addded', models.DateTimeField(auto_now_add=True, null=True, verbose_name='added to platform')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='added to platform')),
            ],
        ),
    ]
