# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-19 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='date_release',
            field=models.DateField(blank=True, null=True, verbose_name='date released '),
        ),
    ]
