# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-19 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20190719_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('neck_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date_addded', models.DateTimeField(auto_now_add=True, null=True, verbose_name='added to platform')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='added to platform')),
            ],
        ),
        migrations.AddField(
            model_name='songs',
            name='artists',
            field=models.ManyToManyField(to='resources.artist'),
        ),
    ]
