# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-19 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20190719_1024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artist',
            new_name='Artists',
        ),
    ]
