# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-26 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20190722_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Albums',
            new_name='Album',
        ),
        migrations.RenameModel(
            old_name='Artists',
            new_name='Artist',
        ),
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
        migrations.AlterModelTable(
            name='album',
            table='Albums',
        ),
        migrations.AlterModelTable(
            name='artist',
            table='Artists',
        ),
        migrations.AlterModelTable(
            name='song',
            table='Songs',
        ),
    ]
