# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-26 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0007_auto_20190726_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img_link', models.CharField(default='https://visualpharm.com/assets/99/Smart%20Playlist-595b40b85ba036ed117daac8.svg', max_length=250)),
                ('is_private', models.BooleanField(default=False)),
                ('date_addded', models.DateTimeField(auto_now_add=True, null=True, verbose_name='added to platform')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='added to platform')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PlayLists',
            },
        ),
        migrations.AlterField(
            model_name='album',
            name='img_link',
            field=models.CharField(default='https://image.flaticon.com/icons/png/512/26/26358.png', max_length=250),
        ),
        migrations.AlterField(
            model_name='artist',
            name='img_link',
            field=models.CharField(default='https://www.sccpre.cat/mypng/full/170-1704218_singer-svg-png-icon-free-download-pop-singer.png', max_length=250),
        ),
        migrations.AlterField(
            model_name='song',
            name='img_link',
            field=models.CharField(default='https://image.flaticon.com/icons/png/512/26/26789.png', max_length=250),
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='resources.Song'),
        ),
    ]
