# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-30 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0009_auto_20190729_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albums', models.ManyToManyField(blank=True, null=True, to='resources.Album')),
                ('artists', models.ManyToManyField(blank=True, null=True, to='resources.Artist')),
                ('playlists', models.ManyToManyField(blank=True, null=True, to='resources.PlayList')),
            ],
            options={
                'db_table': 'User Favorites',
            },
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Album'),
        ),
        migrations.AddField(
            model_name='userfavorites',
            name='songs',
            field=models.ManyToManyField(blank=True, null=True, to='resources.Song'),
        ),
        migrations.AddField(
            model_name='userfavorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
