# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-30 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20190730_1055'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userfavorites',
            table='UserFavorites',
        ),
    ]
