# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-01 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_auto_20190801_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='date_release',
        ),
    ]
