# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-01 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_remove_song_date_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
